"""KGQU GO QRKK FQ JUWRCN. DFCGSU GC. OPUKK
CYU VWGD, WDX QUUK CYU LGDX. KGTU NFRV
KGQU CF CYU QRKKUOC ZFCUDCGWK, WDX
QGEYC QFV NFRV XVUWPO. NFR WVU CYU
SUDCUV FQ NFRV RDGTUVOU, WDX NFR SWD
PWMU WDNCYGDE YWZZUD."""